--- # at exmaple
- hosts: web
  user: user
  become: yes
  connection: ssh
  gather_facts: no
 
  tasks:
    - name: scheduling task 
      at:  command='/bin/ls /var/log >/home/user/at1.log'  count=1  units=minutes
