--- # until example 
- hosts: web
  user: user
  connection: ssh
  gather_facts: no
  become: yes
 
  tasks:
    - name: installation of http package 
      action: yum name=httpd state=latest update_cache=yes
    
    - name: check status of httpd service until it fully start
      command: systemctl status httpd.service
      register: result
      until: result.stdout.find("running") != -1 
      retries: 5
      delay: 5
    - debug: msg=result
