--- # tag example 
- hosts: web
  user: user
  connection: ssh
  become: yes
  gather_facts: no

  tasks:
    - name: installation package nginx 
      action: yum name=nginx state=latest 
      tags: 
        - ngnix
    - name: installation package httpd 
      action: yum name=httpd state=latest 
      tags: 
        - httpd
