--- # Error handling example
- hosts: web
  user: user
  connection: ssh
  gather_facts: no
  become: yes
 
  tasks:
   - name: Generating error with wrong command
     command: /bin/notfound
     ignore_errors: yes
   - name: install telnet
     action: yum name=telnet state=latest 
