--- # Nice optimized ansible example
- hosts: web
  user: user
  connection: ssh
  gather_facts: no
  become: yes
  
  vars:
   pkg_name: httpd
 
  tasks:
   - name: installation http package going to start at 
     command: /usr/bin/date 
     register: time_stamp_start
   - debug: var=time_stamp_start
  
   - name: install http package
     action: yum name={{ pkg_name }} state=latest update_cache=yes  
     notify: Restart httpd

   - name: installation of http package finished at 
     command: /usr/bin/date 
     register: time_stamp_finish
   - debug: var=time_stamp_finish

  handlers:
   - name: Restart httpd
     action: service name=httpd state=restarted enabled=yes

  
