--- # local action 

- hosts: 127.0.0.1
  user: user
  become: yes
  gather_facts: no
  connection: local
  
  tasks:
   - name: install telnet
     action: yum name=telnet state=latest update_cache=yes
