--- #Includes
- hosts: web
  connection: ssh
  user: user
  become: yes
  gather_facts: no
  
  tasks:
   - include: plays/include.yml
  
   - name: telnet installed or not
     raw: yum list installed | grep telnet >> /home/user/pkgs.log
