--- # until 
- hosts: web
  user: user
  connection: ssh
  become: yes
  gather_facts: no
 
  tasks:
    - name: install httpd
      action: yum name=httpd state=latest update_cache=yes

    - name: Check httpd service running or not 
      command: systemctl status httpd
      register: status
      until: status.stdout.find('running') != -1 
      retries: 5
      delay: 5
    - debug: msg={{ status }}
