--- # host discrete 
- hosts: web
  user: user
  connection: ssh
  become: yes
  gather_facts: no

  tasks:
   - include: plays/tasks.yml
  
   - name: verify installed package
     raw: yum list installed | grep telnet >> /home/user/pkg.log
        
