---
# tasks file for webservers
- name: install lynx and telnet
  action:  yum name={{ item }} state=latest  update_cache=yes
  with_items: 
    - telnet
    - lynx
  when: ansible_os_family == "RedHat"
- name: Install apache on Redhat/Centos
  action:  yum name={{ apache_redhat }} state=latest 
  when:  ansible_os_family == "RedHat" 
  notify: Restart httpd

- name: Install apache On debain 
  action: apt name={{ apache_debian }} state=latest
  when: ansible_os_family == "Debian"
  notify: Restart apache2

- name: configure /home/user/test.conf
  template: src=/home/user/Playbook/Roles/roles/webservers/files/test.conf.j2 dest=/home/user/test.conf mode=755 owner=user group=user
