- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  vars:
    UNIQUE_BUCKET_NAME: your-bucket-name
  tasks:
    - name: Create new S3 bucket
      aws_s3:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        bucket: "{{ UNIQUE_BUCKET_NAME }}"
        mode: create
    - name: Add file to bucket
      aws_s3:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        bucket: "{{ UNIQUE_BUCKET_NAME }}"
        mode: put
        object: /testfile.txt
        src: /home/ansible/testfile.txt
