- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Get instance facts
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"  
        ec2_region: "{{ AWS_REGION }}"
        filters: 
          instance-state-name: stopped
      register: ec2_facts
    - debug:
        var: ec2_facts
    - debug:
        var: ec2_facts.instances[0].instance_id
