- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: remove old key
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: my_keypair
        state: absent
    - name: create a new ec2 keypair
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: my_keypair
      register: keypair
    - debug:
        var: keypair
    - name: write new private key to file locally
      lineinfile:
        create: yes
        path: /home/ansible/keypair.pem
        line: "{{ keypair.key.private_key }}"
        mode: 0600
